# Generated by Django 5.0 on 2023-12-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
