# Generated by Django 5.0 on 2023-12-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_list_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
